{
  "report_id": "PENTEST-20250905-155828",
  "target": "http://localhost:8000",
  "start_time": "2025-09-05T15:58:03.738285",
  "end_time": "2025-09-05T15:58:28.032729",
  "total_tests": 17,
  "passed_tests": 0,
  "failed_tests": 1,
  "error_tests": 16,
  "critical_findings": 1,
  "high_findings": 0,
  "medium_findings": 0,
  "low_findings": 0,
  "summary": "CRÍTICO: 1 vulnerabilidades críticas encontradas",
  "recommendations": [
    "URGENTE: Corregir vulnerabilidades críticas inmediatamente"
  ],
  "results": [
    {
      "test_id": "NET-001",
      "test_name": "Rate Limiting",
      "category": "network",
      "severity": "low",
      "status": "error",
      "description": "Error al probar rate limiting: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D32EA0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:07.792375",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "CRYPTO-001",
      "test_name": "Uso de HTTPS",
      "category": "cryptography",
      "severity": "critical",
      "status": "failed",
      "description": "API no usa HTTPS",
      "evidence": [
        "URL: http://localhost:8000"
      ],
      "recommendation": "Implementar HTTPS obligatorio",
      "timestamp": "2025-09-05T15:58:03.740326",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "CRYPTO-002",
      "test_name": "Headers de Seguridad",
      "category": "cryptography",
      "severity": "low",
      "status": "error",
      "description": "Error al verificar headers: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/stats (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D32D70>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:07.792886",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "CONFIG-001",
      "test_name": "Información del Servidor",
      "category": "configuration",
      "severity": "low",
      "status": "error",
      "description": "Error al verificar headers: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/stats (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D6CCB0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:11.837981",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "AUTH-001",
      "test_name": "Autenticación Requerida",
      "category": "authentication",
      "severity": "medium",
      "status": "error",
      "description": "Error al probar autenticación: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D59160>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad y configuración",
      "timestamp": "2025-09-05T15:58:07.792590",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "AUTH-002",
      "test_name": "API Key Inválida Rechazada",
      "category": "authentication",
      "severity": "medium",
      "status": "error",
      "description": "Error al probar API key inválida: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0E140>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:11.854196",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "BIZ-001",
      "test_name": "Funcionalidad Cifrado/Descifrado",
      "category": "business_logic",
      "severity": "medium",
      "status": "error",
      "description": "Error al probar lógica de negocio: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0E580>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad y configuración",
      "timestamp": "2025-09-05T15:58:11.854314",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "AUTHZ-001-_api_v1_encrypt",
      "test_name": "Endpoint /api/v1/encrypt Protegido",
      "category": "authorization",
      "severity": "medium",
      "status": "error",
      "description": "Error al probar /api/v1/encrypt: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D4E710>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:07.792750",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "AUTHZ-001-_api_v1_decrypt",
      "test_name": "Endpoint /api/v1/decrypt Protegido",
      "category": "authorization",
      "severity": "medium",
      "status": "error",
      "description": "Error al probar /api/v1/decrypt: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0E470>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:11.837710",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "AUTHZ-001-_api_v1_stats",
      "test_name": "Endpoint /api/v1/stats Protegido",
      "category": "authorization",
      "severity": "medium",
      "status": "error",
      "description": "Error al probar /api/v1/stats: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/stats (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0E250>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:15.920613",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "AUTHZ-001-_api_v1_audit",
      "test_name": "Endpoint /api/v1/audit Protegido",
      "category": "authorization",
      "severity": "medium",
      "status": "error",
      "description": "Error al probar /api/v1/audit: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/audit (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0DF20>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:19.969226",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "INPUT-001",
      "test_name": "Validación de Entrada Maliciosa 1",
      "category": "input_validation",
      "severity": "low",
      "status": "error",
      "description": "Error al probar entrada: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D4EAD0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:07.793001",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "INPUT-002",
      "test_name": "Validación de Entrada Maliciosa 2",
      "category": "input_validation",
      "severity": "low",
      "status": "error",
      "description": "Error al probar entrada: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0E690>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:11.837884",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "INPUT-003",
      "test_name": "Validación de Entrada Maliciosa 3",
      "category": "input_validation",
      "severity": "low",
      "status": "error",
      "description": "Error al probar entrada: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0ECF0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:15.880556",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "INPUT-004",
      "test_name": "Validación de Entrada Maliciosa 4",
      "category": "input_validation",
      "severity": "low",
      "status": "error",
      "description": "Error al probar entrada: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0E360>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:19.922389",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "INPUT-005",
      "test_name": "Validación de Entrada Maliciosa 5",
      "category": "input_validation",
      "severity": "low",
      "status": "error",
      "description": "Error al probar entrada: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0C270>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:23.972025",
      "target": "http://localhost:8000"
    },
    {
      "test_id": "INPUT-006",
      "test_name": "Validación de Entrada Maliciosa 6",
      "category": "input_validation",
      "severity": "low",
      "status": "error",
      "description": "Error al probar entrada: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/v1/encrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028907D0D6A0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))",
      "evidence": [],
      "recommendation": "Verificar conectividad",
      "timestamp": "2025-09-05T15:58:28.032381",
      "target": "http://localhost:8000"
    }
  ]
}